services:
  - type: web
    name: invest-calc
    env: docker
    repo: https://github.com/Ikul23/invest-calc
    branch: main
    dockerContext: .
    dockerfilePath: docker/php/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:cR3SiE+tFb+ohMIVSaksUuGyQheafmORC2gP7dR4Z20=
      - key: APP_URL
        value: https://invest-calc-2ypa.onrender.com
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: warning

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.hhdqjitrsixdedotpgfq.supabase.co
      - key: DATABASE_URL
        value: postgresql://postgres:drqMdv87kSgtFnwm@db.hhdqjitrsixdedotpgfq.supabase.co:5432/postgres
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: drqMdv87kSgtFnwm

      - key: MAIL_FROM_ADDRESS
        value: kompaniya.gisplyus@bk.ru

      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: local
