services:
  - type: web
    name: invest-calc
    env: docker
    repo: https://github.com/Ikul23/invest-calc
    branch: main
    dockerContext: .
    dockerfilePath: docker/php/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: ENV_FILE
        value: .env.production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvv8f7q4d50c73apdn3g-a.pg.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: investments_calculator_db
      - key: DB_USERNAME
        value: investments_calculator_db_user
      - key: DB_PASSWORD
        sync: false
