services:
  - type: web
    name: invest-calc
    env: docker
    dockerCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    startCommand: "/start.sh"
    repo: https://github.com/Ikul23/invest-calc
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: base64:cR3SiE+tFb+ohMIVSaksUuGyQheafmORC2gP7dR4Z20=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://invest-calc-2ypa.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cvv8f7q4d50c73apdn3g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: investments_calculator_db
      - key: DB_USERNAME
        value: investments_calculator_db_user
      - key: DB_PASSWORD
        value: aIx5iIeApKq1xw0Bn02KHjgqtNNUSdW9

      - key: MAIL_FROM_ADDRESS
        value: kompaniya.gisplyus@bk.ru

      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: FILESYSTEM_DISK
        value: local
